#!/bin/zsh

PG_PASSWORD=$(cat /dev/urandom| tr -dc 'a-zA-Z0-9' | fold -w 20| head -n 1)
curl -X PUT -v localhost:8500/v1/kv/system_variables/pg_password -d "$PG_PASSWORD"

/sbin/setuser netengine /usr/lib/postgresql/9.3/bin/pg_ctl init -o "-E UTF8" -D /shared-data/postgresql
/sbin/setuser netengine /usr/lib/postgresql/9.3/bin/pg_ctl start -w -D /config -l /shared-logs/postgresql.log
/sbin/setuser netengine psql --dbname postgres --host /config --username netengine -c "alter user netengine with password '$PG_PASSWORD';"
/sbin/setuser netengine /usr/lib/postgresql/9.3/bin/pg_ctl stop -w -D /config -l /shared-logs/postgresql.log
